#!/usr/bin/env python3
"""Generate src/coastline_data.h from a Natural Earth coastline GeoJSON.

Reads LineString / MultiLineString features, simplifies each line with
Douglas-Peucker, and emits a compact C array of int16 coordinates
(degrees * 100, i.e. ~1.1 km resolution) plus a polyline-length index.

Usage:
    python3 tools/gen_coastline.py /tmp/ne_50m_coastline.geojson src/coastline_data.h

Source data: Natural Earth (public domain). https://www.naturalearthdata.com/
"""
import json
import sys

# Douglas-Peucker tolerance in degrees. 0.006 deg ~= 0.7 km — fine enough that the
# coastline reads as a smooth curve even at the 10-30 km ranges. Use the 1:10m
# Natural Earth coastline as input; 1:50m is too coarse (only ~5 vertices within
# 30 km of a coastal home). Coarser tol = fewer points (smaller header) but blockier.
TOLERANCE_DEG = 0.0025
MIN_POINTS = 2            # drop polylines shorter than this after simplification
SCALE = 180.0            # degrees -> int16: lon*180 in [-32400,32400] still fits int16 (~0.6 km res)


def perp_dist(p, a, b):
    """Perpendicular distance of point p from segment a-b (in degree units)."""
    ax, ay = a
    bx, by = b
    px, py = p
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return ((px - ax) ** 2 + (py - ay) ** 2) ** 0.5
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    cx, cy = ax + t * dx, ay + t * dy
    return ((px - cx) ** 2 + (py - cy) ** 2) ** 0.5


def douglas_peucker(pts, tol):
    if len(pts) < 3:
        return pts
    # iterative stack-based DP to avoid recursion limits on long lines
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        lo, hi = stack.pop()
        dmax, idx = 0.0, -1
        for i in range(lo + 1, hi):
            d = perp_dist(pts[i], pts[lo], pts[hi])
            if d > dmax:
                dmax, idx = d, i
        if idx != -1 and dmax > tol:
            keep[idx] = True
            stack.append((lo, idx))
            stack.append((idx, hi))
    return [pts[i] for i in range(len(pts)) if keep[i]]


def iter_lines(geom):
    t = geom["type"]
    if t == "LineString":
        yield geom["coordinates"]
    elif t == "MultiLineString":
        for line in geom["coordinates"]:
            yield line


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ne_50m_coastline.geojson"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/coastline_data.h"

    with open(src) as f:
        gj = json.load(f)

    polylines = []          # list of [(lon,lat), ...] simplified
    raw_pts = 0
    for feat in gj["features"]:
        geom = feat.get("geometry")
        if not geom:
            continue
        for line in iter_lines(geom):
            raw_pts += len(line)
            simp = douglas_peucker([(c[0], c[1]) for c in line], TOLERANCE_DEG)
            if len(simp) >= MIN_POINTS:
                polylines.append(simp)

    # flatten to int16, clamping to valid ranges
    coords = []             # int16 pairs: lat_s, lon_s
    lengths = []
    for pl in polylines:
        n = 0
        for lon, lat in pl:
            lat_s = max(-int(90 * SCALE),  min(int(90 * SCALE),  round(lat * SCALE)))
            lon_s = max(-int(180 * SCALE), min(int(180 * SCALE), round(lon * SCALE)))
            coords.append(lat_s)
            coords.append(lon_s)
            n += 1
        lengths.append(n)

    total_pts = len(coords) // 2
    with open(dst, "w") as f:
        f.write("// Auto-generated by tools/gen_coastline.py — DO NOT EDIT.\n")
        f.write("// Source: Natural Earth 1:10m coastline (public domain).\n")
        f.write("// Coordinates are int16 degrees*%d (lat,lon pairs). %d polylines, %d points.\n"
                % (int(SCALE), len(lengths), total_pts))
        f.write("// Simplified with Douglas-Peucker tol=%.3f deg (from %d raw points).\n"
                % (TOLERANCE_DEG, raw_pts))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define COAST_SCALE %d\n" % int(SCALE))
        f.write("#define COAST_NUM_POLYS %d\n" % len(lengths))
        f.write("#define COAST_NUM_PTS %d\n\n" % total_pts)

        f.write("// Points per polyline (walk COAST_PTS sequentially).\n")
        f.write("static const uint16_t COAST_POLY_LEN[COAST_NUM_POLYS] = {\n")
        for i in range(0, len(lengths), 16):
            f.write("  " + ",".join(str(x) for x in lengths[i:i + 16]) + ",\n")
        f.write("};\n\n")

        f.write("// Flat lat,lon int16 pairs (degrees*COAST_SCALE).\n")
        f.write("static const int16_t COAST_PTS[COAST_NUM_PTS * 2] = {\n")
        for i in range(0, len(coords), 16):
            f.write("  " + ",".join(str(x) for x in coords[i:i + 16]) + ",\n")
        f.write("};\n")

    bytes_total = total_pts * 4 + len(lengths) * 2
    print("polylines: %d" % len(lengths))
    print("points:    %d (from %d raw, %.1f%% kept)" % (total_pts, raw_pts, 100.0 * total_pts / raw_pts))
    print("flash:     ~%.1f KB" % (bytes_total / 1024.0))
    print("written:   %s" % dst)


if __name__ == "__main__":
    main()
