#!/usr/bin/env python3
"""Generate src/airports_data.h from the OurAirports airports.csv.

Keeps large airports (always) and medium airports that have an IATA code, so the
map shows the meaningful/scheduled fields without the tens of thousands of tiny
strips. Emits int16 lat/lon (degrees * 100), a 3-letter IATA code, and a 'large'
flag (only large airports get a label on screen).

Usage:
    python3 tools/gen_airports.py /tmp/airports.csv src/airports_data.h

Source data: OurAirports (public domain). https://ourairports.com/data/
"""
import csv
import sys

SCALE = 100.0


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/airports.csv"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/airports_data.h"

    rows = []
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            t = r["type"]
            iata = (r.get("iata_code") or "").strip().upper()[:3]
            if t == "large_airport":
                large = 1
            elif t == "medium_airport" and iata:
                large = 0
            else:
                continue
            try:
                lat = float(r["latitude_deg"])
                lon = float(r["longitude_deg"])
            except (ValueError, KeyError):
                continue
            lat_s = max(-9000, min(9000, round(lat * SCALE)))
            lon_s = max(-18000, min(18000, round(lon * SCALE)))
            rows.append((lat_s, lon_s, iata, large))

    # large first isn't needed; keep file order. Stats:
    n_large = sum(1 for r in rows if r[3])
    with open(dst, "w") as f:
        f.write("// Auto-generated by tools/gen_airports.py — DO NOT EDIT.\n")
        f.write("// Source: OurAirports (public domain).\n")
        f.write("// %d airports (%d large w/ label, %d medium). lat,lon are int16 deg*%d.\n"
                % (len(rows), n_large, len(rows) - n_large, int(SCALE)))
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define AIRPORT_SCALE %d\n" % int(SCALE))
        f.write("#define AIRPORT_NUM %d\n\n" % len(rows))

        f.write("static const int16_t AIRPORT_LAT[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 18):
            f.write("  " + ",".join(str(r[0]) for r in rows[i:i + 18]) + ",\n")
        f.write("};\n\n")

        f.write("static const int16_t AIRPORT_LON[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 18):
            f.write("  " + ",".join(str(r[1]) for r in rows[i:i + 18]) + ",\n")
        f.write("};\n\n")

        f.write("// 1 = large airport (gets an IATA label), 0 = medium (marker only).\n")
        f.write("static const uint8_t AIRPORT_LARGE[AIRPORT_NUM] = {\n")
        for i in range(0, len(rows), 32):
            f.write("  " + ",".join(str(r[3]) for r in rows[i:i + 32]) + ",\n")
        f.write("};\n\n")

        f.write("// 3-letter IATA code (may be empty for a large airport without one).\n")
        f.write("static const char AIRPORT_IATA[AIRPORT_NUM][4] = {\n")
        for i in range(0, len(rows), 12):
            f.write("  " + ",".join('"%s"' % r[2] for r in rows[i:i + 12]) + ",\n")
        f.write("};\n")

    bytes_total = len(rows) * (2 + 2 + 1 + 4)
    print("airports: %d (%d large, %d medium)" % (len(rows), n_large, len(rows) - n_large))
    print("flash:    ~%.1f KB" % (bytes_total / 1024.0))
    print("written:  %s" % dst)


if __name__ == "__main__":
    main()
